navikt/pensjon-etterlatte-felles

- .deploy/topic-prod.yaml
> Statistikk har tilgang til kafka i prod

- apps/ey-pdfgen/templates/brev/partials/innvilgelse.hbs
> Liten endring i tekst for vedtaksbrev - innvilgelse.

- apps/ey-pdfgen/data/eypdfgen/omstillingsstoenad_v1.json
- apps/ey-pdfgen/templates/eypdfgen/omstillingsstoenad_v1.hbs
- apps/ey-pdfgen/templates/eypdfgen/partials_v2/omstillingsstoenad/andreStoenader.hbs
- apps/ey-pdfgen/templates/eypdfgen/partials_v2/omstillingsstoenad/gjenlevende/forholdTilAvdoede.hbs
- apps/ey-pdfgen/templates/eypdfgen/partials_v2/omstillingsstoenad/gjenlevende/gjenlevende.hbs
- apps/ey-pdfgen/templates/eypdfgen/partials_v2/omstillingsstoenad/gjenlevende/oppholdsland.hbs
- apps/ey-pdfgen/templates/eypdfgen/partials_v2/omstillingsstoenad/gjenlevende/situasjon/andreYtelser.hbs
- apps/ey-pdfgen/templates/eypdfgen/partials_v2/omstillingsstoenad/gjenlevende/situasjon/arbeidssoeker.hbs
- apps/ey-pdfgen/templates/eypdfgen/partials_v2/omstillingsstoenad/gjenlevende/situasjon/arbeidstaker.hbs
- apps/ey-pdfgen/templates/eypdfgen/partials_v2/omstillingsstoenad/gjenlevende/situasjon/etablerer.hbs
- apps/ey-pdfgen/templates/eypdfgen/partials_v2/omstillingsstoenad/gjenlevende/situasjon/selvstendig.hbs
- apps/ey-pdfgen/templates/eypdfgen/partials_v2/omstillingsstoenad/gjenlevende/situasjon/tilbud.hbs
- apps/ey-pdfgen/templates/eypdfgen/partials_v2/omstillingsstoenad/gjenlevende/situasjon/utdanning.hbs
- apps/ey-pdfgen/templates/eypdfgen/partials_v2/omstillingsstoenad/gjenlevende/situasjonenDin.hbs
- apps/ey-pdfgen/templates/eypdfgen/partials_v2/omstillingsstoenad/gjenlevende/sivilstatus.hbs
- apps/ey-pdfgen/templates/eypdfgen/partials_v2/omstillingsstoenad/informasjonOmBarn.hbs
- apps/ey-pdfgen/templates/eypdfgen/partials_v2/omstillingsstoenad/samboer/inntekt.hbs
- apps/ey-pdfgen/templates/eypdfgen/partials_v2/omstillingsstoenad/samboer/samboer.hbs
Avhengig av https://github.com/navikt/pensjon-etterlatte/pull/764
> Oppdater oms template til å matche ny din situasjon

- .github/workflows/.build-frontend.yaml
- .github/workflows/.build.yaml
- .github/workflows/.deploy.yaml
- .github/workflows/.test.yaml
- .github/workflows/app-etterlatte-proxy.yaml
- .github/workflows/app-ey-pdfgen.yaml
- .github/workflows/etterlatte-notifikasjoner.yaml
- .github/workflows/ey-slackbot.yaml
- apps/etterlatte-notifikasjoner/Dockerfile
- apps/etterlatte-proxy/Dockerfile
docker-build-push-actionen frå nais-teamet gir oss mykje gratis, blant anna slsa og sårbarheitssjekken i nais-konsollet.
Vil derfor ha oss over på denne. Bruker med det samme sjansen til å samkøyre byggejobbane med sånn vi gjer det i Gjenny, og bruker litt meir oppdaterte baseimages
> Over på nais-actionen docker-build-push

- .github/workflows/.deploy.yaml
- .github/workflows/app-etterlatte-proxy.yaml
- .github/workflows/app-ey-pdfgen.yaml
- .github/workflows/etterlatte-notifikasjoner.yaml
- .github/workflows/ey-slackbot.yaml
Ref https://nav-it.slack.com/archives/C01PG1JM9D4/p1702914021504339
> Konfig for å deploye utan å bruke API-nøkkel

- .github/workflows/.build.yaml
- .github/workflows/.test.yaml
- .github/workflows/codeql.yml
- .github/workflows/verify-branches.yaml
- apps/etterlatte-notifikasjoner/Dockerfile
- apps/etterlatte-proxy/Dockerfile
- buildSrc/build.gradle.kts
Vil påvirke utvikleroppsett:
Set projekt i idea til å bruke JDK 21 (temurin)
Set JAVA_HOME for terminal til JDK 21
> Bump JDK til 21.x

- .deploy/topic-prod.yaml
- .deploy/topic.yaml
> Tilgang til etterlatte.dodsmelding for hendelser-samordning

- apps/etterlatte-proxy/src/main/kotlin/auth/Authentication.kt
Er kanskje litt strengt av code security at deprecated metode gir sikkerheitsissue, men fint å få oppdatert uansett
https://github.com/navikt/pensjon-etterlatte-felles/security/code-scanning/1
> Rettar sikkerheitsissue

- apps/etterlatte-proxy/src/main/kotlin/auth/ClientCredentialAuthProvider.kt
- apps/etterlatte-proxy/src/main/kotlin/auth/DefaultOauth2HttpClient.kt
- gradle/libs.versions.toml
samt etterlatte-libs, pga samme oppdatering der
> Bump nav-token-support 3.2.0 -> 4.1.0

- .deploy/topic-prod.yaml
- .deploy/topic.yaml
Tar gjerne innspill på navn på ny app! 
Har (inntil videre) landet på navnet "tidshendelser", og ikke f.eks. "aldersoverganger". Sistnevnte skal jo håndteres, men det skal også saker på OMS der det har gått x antall måneder siden dødsfallet. "Hendelser" blir for generisk, og ymse andre artignavn som "tidsmaskin", "motor/macchina" osv føles kanskje litt feil ettersom det ikke egentlig er altfor mye som _utføres_ av denne appen.
> EY-3355 Tilgang til kafka for ny app for å håndtere "forutsette" hendelser

- apps/ey-pdfgen/data/eypdfgen/omstillingsstoenad_v1.json
- apps/ey-pdfgen/templates/eypdfgen/partials_v2/omstillingsstoenad/gjenlevende/inntekt/inntekt.hbs
- gradle/libs.versions.toml
**Common versjon vil bli byttet ut før merge**
> EY-3372: Oppdater brev til å passe ny common

- apps/ey-pdfgen/data/eypdfgen/omstillingsstoenad_v1.json
- apps/ey-pdfgen/templates/eypdfgen/partials_v2/omstillingsstoenad/gjenlevende/inntekt/pensjon.hbs
Krever endring av common: [PR-64](https://github.com/navikt/pensjon-etterlatte-libs/pull/64)
> EY-3555: Vis utland hvis det er valgt

- buildSrc/src/main/kotlin/etterlatte.common.gradle.kts
Libs brukes ikke lenger i felles.
> Fjerne maven-kobling mot etterlatte-libs

- apps/etterlatte-proxy/.nais/dev.yaml
- apps/etterlatte-proxy/.nais/prod.yaml
- apps/etterlatte-proxy/import-vault-token.sh
- apps/etterlatte-proxy/src/main/resources/application.conf
- https://nav-it.slack.com/archives/C03793FA1EE/p1655969283660739?thread_ts=1655966091.732049&cid=C03793FA1EE
- https://nav-it.slack.com/archives/C054SA92WR4/p1702963699181499?thread_ts=1702906495.364139&cid=C054SA92WR4
- https://nav-it.slack.com/archives/C03793FA1EE/p1712840953599089?thread_ts=1712836734.448119&cid=C03793FA1EE
> EY-3389 srvbarnepensjon -> srvetterlatte

- apps/etterlatte-proxy/src/main/kotlin/config/SimuleringOppdragConfig.kt
- apps/etterlatte-proxy/src/main/kotlin/config/SoapSecurityMaskSensitiveHelper.kt
- apps/etterlatte-proxy/src/main/kotlin/config/TilbakekrevingConfig.kt
- apps/etterlatte-proxy/src/main/kotlin/routes/SimuleringOppdragRoute.kt
Slippe å gå til kibana e.l. for å se hva (validerings-)feilen er
- Samt lagt til scrambling av felt som inneholder fnr, samt sikkerhet (som inneholder full SAML)
- [eksempel](https://logs.adeo.no/app/r?l=DISCOVER_SINGLE_DOC_LOCATOR&v=8.12.2&lz=N4IglgdgJgpgHiAXCAnANhmgLADgMYAMAtCjgQIZECMVMKROAzBUTFQOwBGnU2nWUTiAA0IAE4B7AO4BJaPCQgANhIDmAZwAu5dQAsi5AA6H1RTTC1ECBZigBMI8dJlRFugF6GA1gFEZOACEALTBGACVNAGEAFQArAE9yVSlHMRgAMxgxNLFFAHojQzyoMHU8CQA3LIBiPIB%2BAH1VAF4ACnSwJXMxdUQAQlaASmFNMABbGER2yTHECGlqAFYxkYk56UHBgDIG8jbypQBXMYhegYn1dSSYYRgICrwlHXVhJRgqpWFCpTA8clGJBBhLoJFphOUINpIFlhh0ulkzq1WgByAAkWn%2BMGRUy0EjSiEKAGVtOZhhNtFNyD8dP0gSUrpw3lB%2BulhJBYHBEMj0JhcIQSGRKDQ6AxmJQ2FweHwBJxkcIvDB4ohHoctFlhBAYKpMSzhIZyGJyGNeq0AI6HLJK2AVIjpS7DTTxQyTQy6Q3qGDDc2WqZjf54XQNV3uyatFVqsSIa22%2B2bYQo9EkrE4zR4yZEpNkmAU1pU …
> Returnere detaljer fra simuleringsfeil

- apps/etterlatte-proxy/.nais/dev.yaml
- apps/etterlatte-proxy/.nais/prod.yaml
PR ~~coming up~~ for flyttingen i saksbehandling, https://github.com/navikt/pensjon-etterlatte-saksbehandling/pull/4644
> EY-3398 Endret triggende app for simulering

- apps/ey-pdfgen/.nais/dev.yaml
- apps/ey-pdfgen/.nais/prod.yaml
- apps/ey-pdfgen/data/notat/tom_mal.json
- apps/ey-pdfgen/templates/notat/tom_mal.hbs
Tom mal i pdfgen som kan lese Slate-format
> EY-3728 Tom mal for notat

- apps/ey-pdfgen/data/eypdfgen/barnepensjon_v2.json
- apps/ey-pdfgen/templates/eypdfgen/partials_v2/common/utbetalingsinformasjon/utbetalingsinformasjon.hbs
Trengs for både [OMS](https://github.com/navikt/pensjon-etterlatte/pull/1273) og BP
> Ny versjon av skattetrekk

- apps/etterlatte-proxy/src/main/kotlin/config/Config.kt
Fallback-strategien for brukarnamn og passord er litt kjip. Vi vil ikkje at vi skal hamne inn der for dev og prod, men som koden er i main no så vil vi ikkje merke det før nokon prøver å gjera eit proxy-kall. Synes heller ikkje det var så eksplisitt
Formålet med fallbackane er å kunne utvikle lokalt, så innfører heller eit skilje i koden mellom lokal utvikling og dev/prod, ved å bruke NAIS_CLUSTER_NAME-miljøvariabelen (samme konseptet som i Gjenny-koden)
> Eksplisitt skilje lokal utvikling og dev/prod

- apps/ey-pdfgen/Dockerfile
Ref https://console.nav.cloud.nais.io/team/etterlatte/dev-gcp/app/ey-pdfgen/image
> pdfgen-versjon utan debian-sårbarheiter

- apps/ey-pdfgen/README.md
- apps/ey-pdfgen/data/inntektsjustering/inntektsjustering_nytt_aar_v1.json
- apps/ey-pdfgen/templates/inntektsjustering/inntektsjustering_nytt_aar_v1.hbs
> EY-4707 bedre pdf visning av inntekt
